type Team = {
    teamNumber: number;
    avgNoShow: number;
    avgMobility: number;
    avgAutoAmpScored: number;
    avgAutoAmpMissed: number;
    avgAutoSpeakerScored: number;
    avgAutoSpeakerMissed: number;
    // avgAutoAutoFoul: number;
    avgCoopertition: number;
    avgTeleAmpScored: number;
    avgTeleAmpMissed: number;
    avgTeleSpeakerScored: number;
    avgTeleSpeakerMissed: number;
    avgTeleNoteInTrap: number;
    // avgTeleopFoul: number;
    avgEndPosition: number;
    avgClimbedTogether: number;
    avgTimeForIntake: number;
    // avgAmpRating: number;
    // avgSpeakerRating: number;
    // whereDefend: number[];
    avgDefenseScore: number;
    // avgOffenseScore: number;
    avgUnderStage: number;
    avgDied: number;
    avgTippedOver: number;
    avgCards: number;
    gamesPlayed: string[]; 
    whereShot: string[];
    comments: string[];
    foulComments: string[];
    shuttleComments: string[];
   };
   
   export default Team;